server:
  port: 9191
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 376491890129-7uf6m3msjb6jsg0fflq28oa541kbfaqd.apps.googleusercontent.com
            clientSecret: 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
#client-id=376491890129-7uf6m3msjb6jsg0fflq28oa541kbfaqd.apps.googleusercontent.com
#client-secret=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
